

development:
  TWITTER_CONSUMER_KEY:  "xa6EV4jyP639YG9GgeenJaXEW"
  TWITTER_SECRET_CONSUMER_KEY: "mwqiVupUHbvacQBXSXcxqr07p55qUGhJV3DqnCFr8zhRPV4LBi"
  TWITTER_ACCESS_TOKEN: "481909236-bp73sK3J2ClXxw0IQaBJYC1triGOMB0aNPSrw0vm"
  TWITTER_ACCESS_TOKEN_SECRET: "sWnV6BwSELAe1nMnVJNRaPRTo6YhrA1JCxIWLL4KirHHM"

test: 
  TWITTER_CONSUMER_KEY:  "xa6EV4jyP639YG9GgeenJaXEW"
  TWITTER_SECRET_CONSUMER_KEY: "mwqiVupUHbvacQBXSXcxqr07p55qUGhJV3DqnCFr8zhRPV4LBi"
  TWITTER_ACCESS_TOKEN: "481909236-bp73sK3J2ClXxw0IQaBJYC1triGOMB0aNPSrw0vm"
  TWITTER_ACCESS_TOKEN_SECRET: "sWnV6BwSELAe1nMnVJNRaPRTo6YhrA1JCxIWLL4KirHHM"

# production:
#   domain_name: "http://www.safetweets.xyz"
